### ISSUE TITLE
Unitty resolve UnityPageNavigationService error

### ISSUE THREAD

**Issue by jackyuan2010** [PrismLibrary/Prism-Samples-Forms#1]
I am a newer in xamarin and prism, when i try to create a cross platform project with xamarin and prism.I encounter a problem.this is my app entrance. the version of prism.form is 6.1-pre5, the version of prism.unity is 6.2-pre3, 
public class App : PrismApplication {
    public App()
    {
        // The root page of your application
    }

    protected override void OnStart()
    {
        // Handle when your app starts
    }

    protected override void OnSleep()
    {
        // Handle when your app sleeps
    }

    protected override void OnResume()
    {
        // Handle when your app resumes
    }

    protected override void InitializeModules()
    {
    }

    protected override void OnInitialized()
    {
        NavigationService.NavigateAsync<MainPage>();
    }

    protected override void RegisterTypes()
    {
        Container.RegisterTypeForNavigation<MainPage>();
    }
}

} 
built successful. but when I run the App,I get a exception:Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "Prism.Unity.Navigation.UnityPageNavigationService", name = "(none)".

Exception occurred while: Calling constructor Prism.Unity.Navigation.UnityPageNavigationService(Microsoft.Practices.Unity.IUnityContainer container).

Exception is: MissingMethodException - Method 'PageNavigationService..ctor' not found.

At the time of the exception, the container was:

Resolving Prism.Unity.Navigation.UnityPageNavigationService,(none)

Calling constructor Prism.Unity.Navigation.UnityPageNavigationService(Microsoft.Practices.Unity.IUnityContainer container) .

Is there anything wrong?

**Comment by brianlagunas** [comment]
You're using the wrong NuGet package.  You need to be using Prism.Unity.Forms
