### ISSUE TITLE
Prism Xamarin.Forms MasterDetail single instance of detail pages

### ISSUE THREAD

**Issue by rob-burrus** [PrismLibrary/Prism-Samples-Forms#10]
Trying to create a Xamarin.Forms project with Prism and use a MasterDetail page. I have my MasterDetail set up following the HelloWorld example found in "Sandbox". 
The issue is that every time you navigate to a detail page, a new viewmodel and view instance is created. Per Xamarin.Forms docs, you could hold onto a single instance of a view/viewmodel by maintaining a list of these views in your top level masterdetail view code behind (or view model). Then when a user clicks on a Master option, the stored view/viewmodel instance is navigated to - no recreating of views and their viewmodels. But this strategy seems to break with Prism, because navigation is done by string / uri, so we can't navigate to a page that we maintain in a list. Or can we? Wondering if I'm missing something

**Comment by brianlagunas** [comment]
You're not missing anything. Prism intentionally does not support this. If you need this ability, you can handle this yourself in code behind using the native API, and use Prism for everything else.
