### ISSUE TITLE
Prism latest source code projects not loading in Microsoft Visual Studio Enterprise 2019 Version 16.6.3 framework 4.8

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism-Samples-Forms#104]
I downloaded the lated Prism source code. When trying to open the PrismLibrary.sln project none of the Prism projects loaded as showin the image. I did not even see a Prism .Net Framework project only a core project.
I am using
Microsoft Visual Studio Enterprise 2019
Version 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Version 4.8.03752.

Is there someing I am missing?

![prism7_2_not_loaded](https://user-images.githubusercontent.com/22349374/90207470-f8b55180-ddab-11ea-81b1-3b40ef99fc8b.png)

**Comment by dansiegel** [comment]
This is in the wrong repository, and is ultimately not a valid issue for Prism. This is most likely caused by a missing sdk on your system. You would need to try to force a load to get the error message that would tell you what the issue is.
