### ISSUE TITLE
Understanding for using IInitializeAsync

### ISSUE THREAD

**Issue by kerbooo** [PrismLibrary/Prism-Samples-Forms#105]
Hello, I have 2 pages. Basically structure is as following. 

**FirstPageViewModel**

...
`await NavigationService.NavigateAsync("SecondPage");`
...

**SecondPageViewModel**

```
public async Task InitializeAsync(INavigationParameters parameters)
{
	await LoadPageDataAsync(parameters);
}


private async Task LoadPageDataAsync(INavigationParameters parameters)
{
	try
	{
		// in here I am getting data from remote server with an api Interface using await task. But sometime it can be broken
	}
	catch(Exception exception)
	{
		 var confirm = await PageDialogService.DisplayAlertAsync("Sorry", "Data did not load", "Try Again", "Close");

		if (confirm)
		{
			await LoadPageDataAsync(parameters);
		}
		else
		{
			// that is not working because when I get current page name with PageUtilities.GetCurrentPage(Application.Current.MainPage) that's output seems still "FirstPage" 
			 await NavigationService.GoBackAsync();
		}
	}
}

```

Summarizes What I want to do, I do not want to leave from **FirstPage** when data broken in **SecondPage** before **SecondPage** appearing.  I mean I do not want show **SecondPage** Actually  I don't know this approach is true or not. Thank you in advance for support.

**Comment by dansiegel** [comment]
@kerbooo we already have a [sample that handles various initialization requirements](https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/13-ViewModelInitialization). Note that you should NEVER use IInitializeAsync for any ViewModel that will be called on your initial navigation.
