### ISSUE TITLE
FinalizeExtension() method is empty method; PrismApplicationBase's  Initialize() method line of code  _containerExtension.FinalizeExtension();

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism-Samples-Forms#108]
In the PrismApplicationBase's  Initialize() method there is this line of code:
  _containerExtension.FinalizeExtension()

The FinalizeExtenstion method is just an  void method with no code.
Is there suppose to be some code in this method, or should the methode be made virtual?

 public abstract class PrismApplicationBase : Application
    {
...........................
............
        /// <summary>
        /// Runs the initialization sequence to configure the Prism application.
        /// </summary>
        protected virtual void Initialize()
        {
.......................................
.............................
            **_containerExtension.FinalizeExtension();**

    class UnityContainerExtension : IContainerExtension<IUnityContainer>, IContainerInfo
    {.........
     /// <summary>
        /// Used to perform any final steps for configuring the extension that may be required by the container.
        /// </summary>
        public void FinalizeExtension() { }

**Comment by dansiegel** [comment]
@stevensrf11 the samples repo issues is not the place to ask questions. You can ask questions publicly on StackOverflow, on Prism Slack or on the Sponsor Discord
