### ISSUE TITLE
Add possibility to navigate to page, *without duplicating* it on NavigationStack.

### ISSUE THREAD

**Issue by Szymaniuk** [PrismLibrary/Prism-Samples-Forms#11]
Actually it's not a bug, just to be clear.
On my previous project, when I didn't use Prims, but OOTB XF, I'd to extend NavigationService, so that navigation between pages, was "duplicate aware".
In a few words - it was about to to Push page, without duplicate, in order to avoid user multiple time clicking on button (that invokes navigation) + avoid *disabling* this button clicking.

I saw at Xamarin Forms forum, that it's common case, and multiple people has already workarounded this.

I used such fragment of code, to avoid pushing Page with duplicates:

```
private async Task PushAsyncWithoutDuplicate(Page page)
{
	if (MainPage.Navigation?.NavigationStack != null)
	{
		// Prevent multiple puting same page at *NavigationStack*
		if (MainPage.Navigation.NavigationStack[MainPage.Navigation.NavigationStack.Count - 1].GetType() != page.GetType())
		{
			// Push *page* to *NavigationStack*
			await MainPage.Navigation.PushAsync(page);
		}
	}
}
```

What do you thing, about adding additional parameter to **INavigationService** methods - just simple **bool allowDuplicate = true**, which behind will prevent pushing same page at *NavigationStack*, as in above example?

**Comment by brianlagunas** [comment]
This is not the correct solution to the problem.  Not only is this not a good approach, but it is also not a reliable solution.  The better approach is to either disable the button or prevent the call the NavigateAsync in your ViewModel logic.
