### ISSUE TITLE
Exception ContentControl is not registered in the region adapter mappings? 

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism-Samples-Forms#112]
I have a region name attached it a ContentControl via  a static string binding  in the Shell,xaml file as shown below:
 <ContentControl   prism:RegionManager.RegionName="{x:Static infrastructure:RegionNames.ContentRegion}" 
                                        Margin="1,3,3,3" />

The static string is defined as shown:
namespace IGOutlook.Infrastructure
{
    public static class RegionNames
    {
        public const string RibbonTabRegion = "RibbonTabRegion";
        public const string OutlookBarGroupRegion = "OutlookBarGroupRegion";
        public const string ContentRegion = "ContentRegion";

    }
}

When I run the application and Exception is thrown complaining about the ContentControl not being registered.
Any reason you can think of while this occurrs?

I have two custom controls also in the Shell.xaml file and they use the two remaining static strings in the RegionNames class
to bind to the RegionName and  no exception occurs on either of the two controls:
<dxn:NavBarControl prism:RegionManager.RegionName="{x:Static infrastructure:RegionNames.OutlookBarGroupRegion}" 
                                           DockPanel.Dock="Left" 
                                           Width="200" 
                                            />
 <dxr:RibbonControl 
                                       RibbonStyle="Office2010"
                                       DockPanel.Dock="Top"
                                       prism:RegionManager.RegionName="{x:Static infrastructure:RegionNames.RibbonTabRegion}">

I have attached the Shell.xaml file in the attached zip file.
I am using Devexpress controls for the custom controls.
[Shell.xaml.zip](https://github.com/PrismLibrary/Prism-Samples-Forms/files/5250001/Shell.xaml.zip)

-ContentControl  Exception  Not Registered In Region Adapter
 'ContentRegion'. The exception was: System.Collections.Generic.KeyNotFoundException: 
The IRegionAdapter for the type System.Windows.Controls.ContentControl is not registered in the region adapter mappings. 
You can register an IRegionAdapter for this control by overriding the ConfigureRegionAdapterMappings method in the bootstrapper.
   at Prism.Regions.RegionAdapterMappings.GetMapping(Type controlType) in C:\Prism-7.2.0.1422\Prism-7.2.0.1422\Source\Wpf\Prism.Wpf\Regions\RegionAdapterMappings.cs:line 63
   at Prism.Regions.Behaviors.DelayedRegionCreationBehavior.CreateRegion(DependencyObject targetElement, String regionName) in C:\Prism-7.2.0.1422\Prism-7.2.0.1422\Source\Wpf\Prism.Wpf\Regions\Behaviors\DelayedRegionCreationBehavior.cs:line 127.

**Comment by stevensrf11** [comment]
Here is the shell.xaml file code
<dxr:DXRibbonWindow 
    xmlns:dxr="http://schemas.devexpress.com/winfx/2008/xaml/ribbon" 
                     x:Class="IgOutlook.Application.Shell"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:prism="http://prismlibrary.com/"
        xmlns:local="clr-namespace:IgOutlook.Application"
        xmlns:dxn="http://schemas.devexpress.com/winfx/2008/xaml/navbar"
        xmlns:dxb="http://schemas.devexpress.com/winfx/2008/xaml/bars"
    xmlns:dxc="http://schemas.devexpress.com/winfx/2008/xaml/core"
    xmlns:infrastructure="clr-namespace:IGOutlook.Infrastructure;assembly=IgOutlook.Infrastructure"

    mc:Ignorable="d"
        Title="Shell" Height="300" Width="500">
    <Grid>
        <dxb:BarManager Name="barManager1">
            <dxb:BarManager.Items>
                <dxb:BarButtonItem x:Name="barButtonItem1" Content="BarButtonItem" 
                                       Glyph="{dxc:DXImage 'Images/Actions/Apply_16x16.png'}" 
                                       LargeGlyph="{dxc:DXImage 'Images/Actions/Apply_32x32.png'}"/>
            </dxb:BarManager.Items>
            <DockPanel>
                <dxr:RibbonControl 
                                       RibbonStyle="Office2010"
                                       DockPanel.Dock="Top"
                                       prism:RegionManager.RegionName="{x:Static infrastructure:RegionNames.RibbonTabRegion}">
                    

                    <dxr:RibbonDefaultPageCategory Caption="defaultCategory">

                        <dxr:RibbonPage Caption="Home">
                            <dxr:RibbonPageGroup Caption="Tools"/>
                            <dxr:RibbonPageGroup Caption="Ribbon Page Group">
                                

                            </dxr:RibbonPageGroup>
                        </dxr:RibbonPage>
                        <dxr:RibbonPage Caption="Ribbon Page"/>
                    </dxr:RibbonDefaultPageCategory>

                    <dxr:RibbonPageCategory Caption="Ribbon Category">
                        <dxr:RibbonPage Caption="Ribbon Page"/>
                    </dxr:RibbonPageCategory>

                    <dxr:RibbonControl.ToolbarItems>
                        <dxb:BarButtonItemLink BarItemName="barButtonItem1"/>
                    </dxr:RibbonControl.ToolbarItems>

                </dxr:RibbonControl>
                <DockPanel LastChildFill="True">
                    <dxn:NavBarControl prism:RegionManager.RegionName="{x:Static infrastructure:RegionNames.OutlookBarGroupRegion}" 
                                           DockPanel.Dock="Left" 
                                           Width="200" 
                                            />
                    <ContentControl 
                            prism:RegionManager.RegionName="{x:Static infrastructure:RegionNames.ContentRegion}" 
                                        Margin="1,3,3,3" />
                </DockPanel>
            </DockPanel>
        </dxb:BarManager>
    </Grid>
</dxr:DXRibbonWindow>

**Comment by brianlagunas** [comment]
Questions should be asked on the Prism private slack channel (must be a sponsor) or on a forum like StackOverflow.

**Comment by stevensrf11** [comment]
Ok
