### ISSUE TITLE
Xamarin Forms - HttpClientFactory and dependency injection 

### ISSUE THREAD

**Issue by davecameos** [PrismLibrary/Prism-Samples-Forms#115]
### Description
Hi
This is not really an issue, more like a question.
I would like to register a HttpClientFactory in Xamarin Forms that can be injected in a class from a class Library project that contains all the API calls, is there any samples in this directory? I could not find any.

In .net core I was able to add the service in ConfigureServices startup class like this : 

```
services.AddSingleton<TClientQueries>();
services.AddHttpClient<TClient>("THttpClient",
    x => { x.BaseAddress = new Uri(ctx.Configuration["APIConfiguration:BaseAddress"]); }
).AddPolicyHandler(GetRetryPolicy());
services.AddSingleton<ClientFactory>();
```
#### Sample Feature

Is there an equivalent for this using IContainerRegistry or something more suitable in Prism?

Thanks

**Comment by brianlagunas** [comment]
We do not have a sample of this and there is no equivalent on IContainerRegistry.

**Comment by dansiegel** [comment]
This is possible with either the Prism Container Extensions or Prism Magician, but as @brianlagunas said this isn't something we'll be adding a sample for.

**Comment by davecameos** [comment]
Thank you both. New to xamarin and maybe there is a better way to create the service than a .net core way.

**Comment by dansiegel** [comment]
keep in mind what you're seeing with the AddHttpClient method on IServiceCollection is just an extension method. It's also open source so if you spend a few minutes you can easily create your own extension method that uses IContainerRegistry that matches the magic that the IServiceCollection extension method is doing for you.

**Comment by davecameos** [comment]
Please feel free to remove this comment if it is not a good place, but if I want to use prism dependency injection with a service that implements httpclient, would it be possible? I already got a service, it is just a matter of how to register it in App.xaml.cs

**Comment by dansiegel** [comment]
questions are best asked as a thread in the [Discussions](https://github.com/PrismLibrary/Prism/discussions/new) in the main Prism repo
