### ISSUE TITLE
[Request] Dynamic loading module sucha s "07-Modules - LoadManual" for wpf

### ISSUE THREAD

**Issue by chc7042** [PrismLibrary/Prism-Samples-Forms#117]
### Dynamic load module for main application
is it possible to implement such as "07-Modules - LoadManual" for wpf? basically i need this feature for implement to our mobile application. 

#### Reason for Update
as you might know this dynamic loading feature very helpful to work with our cooperative companion.
i will make main application including basic functionality and our co-worker will use our api and develop their own module which installed our main application.

**Comment by dansiegel** [comment]
The Modules sample already shows you how to dynamically load modules at runtime. 
https://github.com/PrismLibrary/Prism-Samples-Forms/blob/98ec5cbfd41f0685447475548fd67533b542ab6b/10-Modules/src/PrismSample/App.xaml.cs#L36-L39
