### ISSUE TITLE
IActiveAware not working when ContentPage is wrapped into a navigationpage

### ISSUE THREAD

**Issue by reinierkops** [PrismLibrary/Prism-Samples-Forms#18]
When a content page is wrapped in a navigationpage, the IsActive property isn't set.

**Comment by brianlagunas** [comment]
IActiveAware is not meant for use in normal pages.  Only TabbedPages and CarouselPages.

**Comment by reinierkops** [comment]
I mean, when a ContentPage (as child of a tabbed page) is wrapped into a NavigationPage, the event is not triggered.

**Comment by brianlagunas** [comment]
Oh, well why did you say so? :)

I'll check it out.

**Comment by brianlagunas** [comment]
Actually, can you add this to the Prims repo and not the samples repo?  And provide all the details :)

https://github.com/prismlibrary/prism/issues
