### ISSUE TITLE
Unit testing example please

### ISSUE THREAD

**Issue by aphex3k** [PrismLibrary/Prism-Samples-Forms#19]
> We couldn’t find any code matching 'tests'

I couldn't find any documentation how to unit test my Xamarin.Forms App using NUnit with `Prism.Unity.Forms`. Maybe at least a links in the Readme?

**Comment by dansiegel** [comment]
Are you looking to do Unit Tests or UI Tests? Either way it's really not different with Prism than without Prism.

If you want UI Tests just follow the [guide](https://developer.xamarin.com/guides/testcloud/uitest/intro-to-uitest/) from Xamarin

**Comment by aphex3k** [comment]
Unit Tests

**Comment by dansiegel** [comment]
Personally I just use xunit for unit tests... it happens to also be what we use to test Prism Forms, but that's just my personal preference not a unit test requirement. I might suggest that you look at how we [unit test](https://github.com/PrismLibrary/Prism/tree/master/Source/Xamarin/Prism.Unity.Forms.Tests) Prism.Unity.Forms.

**Comment by aphex3k** [comment]
I was going for NUnit (2.6.X) specifically because in Forms that is what the UI Tests are based on as well. This way I don't have to include several unit test frameworks in my solution...

**Comment by dansiegel** [comment]
The unit test framework you use isn't important... you can use whatever you're most comfortable with. looking at how we go able testing Prism.Unity.Forms should give you a good sense though how to construct tests to validate your own ViewModels and Services
