### ISSUE TITLE
HamburgerMenu - please can you add UWP project to the solution

### ISSUE THREAD

**Issue by mdonogma** [PrismLibrary/Prism-Samples-Forms#20]
Looking for starter project for IOS, Droid and UWP that has hamburger menu.

Please could you update the HamburgerMenu with UWP project to.

**Comment by brianlagunas** [comment]
We accept PRs :)

**Comment by mdonogma** [comment]
can you guide on approach - i'll then look at PR.

**Comment by dansiegel** [comment]
There’s really nothing magic about how to do this in UWP. It was an adaptation of the sample from Xamarin Forms with a little Prism spice mixed in. But that does t change how you achieve a Hamburger Menu on any platform. 
https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/navigation/master-detail-page/
https://github.com/xamarin/Xamarin-forms-samples/tree/master/Navigation/MasterDetailPage
