### ISSUE TITLE
viewmodels don't fire if moved to seperate PCL project.

### ISSUE THREAD

**Issue by mdonogma** [PrismLibrary/Prism-Samples-Forms#21]
for Testing purposes we have moved the viewmodels in the sample to Example.ViewModels

however the commands stop firing when the viewmodels are in seperate project?

The PCL with the views does reference the Example.ViewModels project.

guidance needed?

**Comment by brianlagunas** [comment]
if you move them to another project, the naming convention is broken (you're in a different assembly now).  You either need to change the conventions, or explicitly register the VMs with the views.

**Comment by dansiegel** [comment]
To clarify Brian's guidance there... 

```cs
// Easy Way
Container.RegisterTypeForNavigation<ViewA, ViewAViewModel>();

// Harder Way
ViewModelLocationProvider.SetDefaultViewModelFactory( viewType => {
    // Do stuff
    return viewModelType;
});
