### ISSUE TITLE
Is it use InvokeCommandAction in Xamarin.Forms?

### ISSUE THREAD

**Issue by heyixiaoran** [PrismLibrary/Prism-Samples-Forms#23]
In WPF. If I want to call the ListView selecteIitemchanged can use 

`<i:Interaction.Triggers>  
         <i:EventTrigger EventName="SelectedItemChanged">  
             <i:InvokeCommandAction Command="{Binding SelectedChangedCommand}"/>  
         </i:EventTrigger>  
     </i:Interaction.Triggers>  `

to call the command. But in Xamarin.Forms .Is it same ?

**Comment by brianlagunas** [comment]
Please post this question on [StackOverflow](https://stackoverflow.com/questions/tagged/prism)
