### ISSUE TITLE
Autowiring viewmodels fails to resolve dependencies on views (Prism.Unity.Forms)

### ISSUE THREAD

**Issue by less0** [PrismLibrary/Prism-Samples-Forms#24]
While for pages autowiring with Prism.Unity.Forms works flawlessly, it does not seem to work for views. Lets assume a viewmodel with an arbitrary dependency

```
class MyViewViewModel
{
    public MyViewModel(IDependency dependency)
    {
    }
}
```

and the corresponding view

```
<ContentView xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
   x:Class="My.App.Views.MyView"
             xmlns:mvvm="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             mvvm:ViewModelLocator.AutowireViewModel="True">
...
</ContentView>
```

When prism/unity tries to resolve the dependency the following exception is thrown

> Resolution of the dependency failed, type = "My.App.MyViewViewModel", name = "(none)".
> Exception occurred while: Resolving parameter "dependency" of constructor My.App.MyViewViewModel(IDependency).
> Exception is: NullReferenceException - Object reference not set to an instance of an object.

with the stack trace 

> at Microsoft.Practices.Unity.UnityContainer.DoBuildUp (System.Type t, System.Object existing, System.String name, System.Collections.Generic.IEnumerable`1[T] resolverOverrides) [0x0007b] in <ba86a34b2f2c4964b8c588538e94514f>:0 
>   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp (System.Type t, System.String name, System.Collections.Generic.IEnumerable`1[T] resolverOverrides) [0x00000] in <ba86a34b2f2c4964b8c588538e94514f>:0 
>   at Microsoft.Practices.Unity.UnityContainer.Resolve (System.Type t, System.String name, Microsoft.Practices.Unity.ResolverOverride[] resolverOverrides) [0x00000] in <ba86a34b2f2c4964b8c588538e94514f>:0 
>   at Microsoft.Practices.Unity.UnityContainerExtensions.Resolve (Microsoft.Practices.Unity.IUnityContainer container, System.Type t, Microsoft.Practices.Unity.ResolverOverride[] overrides) [0x0000b] in <ba86a34b2f2c4964b8c588538e94514f>:0 
>   at Prism.Unity.PrismApplication.<ConfigureViewModelLocator>b__2_0 (System.Object view, System.Type type) [0x0002a] in <d48531d8cf994cb8b9baff9564ac22d2>:0 
>   at Prism.Mvvm.ViewModelLocationProvider.AutoWireViewModelChanged (System.Object view, System.Action`2[T1,T2] setDataContextCallback) [0x00042] in <c7f0f832ef3946009ad46bccbd859f64>:0 
>   at Prism.Mvvm.ViewModelLocator.OnAutowireViewModelChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00019] in <7a32c28f35024e719a93e31b4d1e3d2a>:0 
>   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.BindableObject+SetValueFlags attributes, System.Boolean silent) [0x00108] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:592 
>   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.BindableObject+SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:386 
>   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:539 
>   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:83 

Registering `MyViewViewModel` with the unity container does not resolve the issue, neither.

**Comment by less0** [comment]
Wrong repo, sorry

**Comment by ouzs** [comment]
hello,are you find the answer of this question?
