### ISSUE TITLE
Unhandled Exception:  Foundation.MonoTouchException: Objective-C exception throw

### ISSUE THREAD

**Issue by marciordonez** [PrismLibrary/Prism-Samples-Forms#26]
Unhandled Exception:  Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch

Error on Main.cs

Line: UIApplication.Main(args, null, "AppDelegate");

**Comment by brianlagunas** [comment]
Sorry, you're going to need to provide more information than that.

**Comment by brianlagunas** [comment]
Closing since there has been no response.
