### ISSUE TITLE
Is TabbedNavigation implementation applicable for WPF?

### ISSUE THREAD

**Issue by 19er** [PrismLibrary/Prism-Samples-Forms#27]
Hello, I wonder if this TabbedNavigation concept is applicable for WPF?

**Comment by brianlagunas** [comment]
No it's not.

**Comment by 19er** [comment]
Could you point any directions for those looking for some implementation like TabbedNavigation in WPF?

**Comment by brianlagunas** [comment]
You can start here: https://www.pluralsight.com/courses/prism-mastering-tabcontrol
