### ISSUE TITLE
Please Update The solution 

### ISSUE THREAD

**Issue by ronakshethia** [PrismLibrary/Prism-Samples-Forms#29]
After Updating the prism version, i am getting the errors at many places,
can you please update the solution with the updated version of prism

**Comment by brianlagunas** [comment]
You can read the release notes to see what has changed.  You can also rely on your IDE intellisense to help you fix your code.

https://github.com/PrismLibrary/Prism/releases/tag/7.0.0-Forms

I am in the middle of working on new samples, so I will not be spending time to update these.
