### ISSUE TITLE
OnNavigatedTo fires twice on MasterDetailPage

### ISSUE THREAD

**Issue by HeikkiDev** [PrismLibrary/Prism-Samples-Forms#30]
Hi, I've copied the HamburgerMenu code sample in a new Xamarin Forms with Prism template solution.

In LoginPage i have a button with the following command code:

await _navigationService.NavigateAsync ("/ MainPage / NavigationPage / ViewA");

MainPage is my MasterDetailPage. In MainPageViewModel the OnNavigatedTo override method fires twice.

Any idea? I´m missing somethig?

My code: https://github.com/HeikkiDev/XamarinFormsPrismHamburger

Thanks in advance.

**Comment by pasteusernamehere** [comment]
I have run into this issue with my own app.  Anyone know why this event is firing twice?  Framework defect?  Any suggested workarounds?

**Comment by HeikkiDev** [comment]
I'm not sure if it's the expected behavior.
My workaround is add a HasInitialized property in my ViewModelBase, like suggested in 'Working with TabbedPage' in Prism docs. I hope this helps you.

[http://prismlibrary.github.io/docs/xamarin-forms/Working-With-TabbedPages.html](url)

**Comment by pasteusernamehere** [comment]
Thanks, I will check it out.
