### ISSUE TITLE
TabbedNavigation example - IsActiveChanged do not work

### ISSUE THREAD

**Issue by alesdvorakcz** [PrismLibrary/Prism-Samples-Forms#36]
I tried to run TabbedNavigation example. IsActive at ChildViewModelBase is correctly set when I change selected tab but it seems like IsActiveChanged event does not work - no Debug.WriteLine record and even breakpoint is not hitted.

I did not make any changes, I just downloaded this example and runned it at android simulator.

**Comment by brianlagunas** [comment]
That has to be manually invoked. It is not invoked by the framework.
