### ISSUE TITLE
Samples for stable release 7.2 

### ISSUE THREAD

**Issue by Im-PJ** [PrismLibrary/Prism-Samples-Forms#37]
Would be great to see the samples for new concepts introduced in 7,2 like Auto View registration, View/ViewModel Initialization, Auto Initialize from navigation parameters, Dialog services etc.

**Comment by dansiegel** [comment]
don't disagree... keep in mind 7.2 was just released... gotta give us time

**Comment by Im-PJ** [comment]
Im sorry this is not an issue. I was not able to make auto view registration work so just pinged here.

**Comment by dansiegel** [comment]
done... additional base templates have been added and will be open for the community to help with

**Comment by Im-PJ** [comment]
Thank you. I'm waiting to know the best implementation for this #55
