### ISSUE TITLE
HamburgerMenu project fails to build iOS

### ISSUE THREAD

**Issue by SittenSpynne** [PrismLibrary/Prism-Samples-Forms#38]
The XamlC task fails, in particular:

```
    /Users/{snip}/Xamarin.Forms.targets(62,3): error MSB4018: System.IO.FileNotFoundException: Could not find file "/Users/{snip}/prism/Prism-Samples-Forms/HamburgerMenu/HamburgerMenu/obj/Debug/HamburgerMenu.dll.mdb"
```

Looks like it's just the ancient version of Xamarin Forms it references isn't compatible with the current Xamarin toolchain.

**Comment by SittenSpynne** [comment]
(I can probably make a PR myself but haven't ever done that before so I'm looking into it!)

**Comment by dansiegel** [comment]
The Hamburger Menu sample is being deprecated and will be removed shortly.
