### ISSUE TITLE
[Update] ReactiveUI + Prism

### ISSUE THREAD

**Issue by RLittlesII** [PrismLibrary/Prism-Samples-Forms#47]
### Sample

[61-ReactiveUI](https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/61-ReactiveUI)
#### Reason for Update

Sample to show how to use ReactiveUI and Prism.

**Comment by dansiegel** [comment]
thanks for the help @RLittlesII I know a lot of people are looking forward to seeing this!

**Comment by luismts** [comment]
> ### Sample
> [61-ReactiveUI](https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/61-ReactiveUI)
> 
> #### Reason for Update
> Sample to show how to use ReactiveUI and Prism.

+1
