### ISSUE TITLE
[Update] 02-ServiceRegistration

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Samples-Forms#49]
### Sample

02-ServiceRegistration

#### Reason for Update

This sample is currently stubbed and needs actual implementation.

TODO

- Show how to register a Transient Service
- Show how to register a Singleton Service
- Have a simple UI that can visualize how the Singleton is always the same and the Transient is getting a new instance each time.

**Comment by almirvuk** [comment]
Can I take this one as well?

**Comment by dansiegel** [comment]
Sounds great... thanks @almirvuk

**Comment by dansiegel** [comment]
fixed in #73
