### ISSUE TITLE
UsingModules not working - incomplete ?

### ISSUE THREAD

**Issue by ChristianRiedl** [PrismLibrary/Prism-Samples-Forms#5]
I expected that _SampleModule_ will load a new page, but nothing happens when I press the button.
SampleModule is only the device independent PCL. 
Isn't it necessary to implement device specific _SampleModule.Droid_, _SampleModule.iOS_ ... ?

**Comment by brianlagunas** [comment]
Which button are you pressing and expecting to show a new page?  You have to load the module first, and then navigate.

**Comment by ChristianRiedl** [comment]
You are right, now I understand how it works.
