### ISSUE TITLE
[Update] 04 Commands

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Samples-Forms#50]
### Sample

- 04-Commands
- 04-CompositeCommands

#### Reason for Update

We actually want to get rid of the 2 projects and combine these to show how to use different aspects of the commands in a single sample

##### Proposed Changes

- Use a Menu Page in a NavigationPage
  - Option to Show the use of the CompositeCommand
  - Option to Show the current `ObservesCanExecute`
  - New pages to show different configuration aspects of DelegateCommand like ObservesProperty
- Delete 04-CompositeCommands

**Comment by brianlagunas** [comment]
I disagree. CompositeCommands are a completely different concept with different features than a normal command. I would prefer to keep samples focused on a specific feature than to mix them
