### ISSUE TITLE
[Update] 07 DialogService

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Samples-Forms#51]
### Sample

07-DialogService

#### Reason for Update

This sample is currently stubbed and needs actual implementation.

TODO

- Add a basic dialog that shows passing of dialog parameters via QueryString and DialogParameters
- Add basic Dialog that has a form that controls the return value of CanCloseDialog

**Comment by hnabbasi** [comment]
I'll take this one ✋

**Comment by dansiegel** [comment]
thanks @hnabbasi
