### ISSUE TITLE
[Update] 14 EventToCommandBehavior

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Samples-Forms#56]
### Sample

14-EventToCommandBehavior

#### Reason for Update

This sample is currently stubbed and needs actual implementation.

TODO

- Show this returning a value from the EventArgs via the `EventArgsPath` property
- Show this returning a value from the EventArgs via a custom `IValueConverter`
- Show this with no value (using DelegateCommand)

**Comment by almirvuk** [comment]
Hi, I would like to help with this one. Can you "assign" it to me :)

**Comment by dansiegel** [comment]
fixed in #72
