### ISSUE TITLE
[Update] 15 PageBehaviorFactory

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Samples-Forms#57]
### Sample

15-PageBehaviorFactory

#### Reason for Update

This sample is currently stubbed and needs actual implementation.

TODO

- Use a custom PageBehaviorFactory
- Set some Platform Specifics / maybe change some colors.

**Comment by almirvuk** [comment]
I would like to implement this one :)

**Comment by almirvuk** [comment]
We can close this one? 🙂
