### ISSUE TITLE
Need example of Prism Xamarin Form Tabbed Page 

### ISSUE THREAD

**Issue by ShahriatHossain** [PrismLibrary/Prism-Samples-Forms#6]
Hi there,
Can anybody help me giving some example tutorial of Prism TabbedPage with MVVM? I am new at Xamarin App development.

**Comment by brianlagunas** [comment]
Can you be more specific?  What exactly is your scenario?

**Comment by ShahriatHossain** [comment]
Hi there,
I am using Prism to make PCL project in Xamarin.Forms. I want to integrate
Tabbed Page where there should be two tabs. Each tab will contain separate
ListView and I want to populate data for each ListView from my ViewModel of
that Tabbed Page. I still have not integrated TabbedPage yet in my project.
So I am little bit confused how to do that and I need a tutorial or an
example so that I can understand.

Regards
--
*Shahriat Hossain*
Sr. Software engineer
ImplevistaBD Pvt. Ltd.
Consultant for Microsoft .net, php and ios/android native app development
Associate member of BCS (Bangladesh Computer Society)

Mobile: +880-1923508304

**Comment by brianlagunas** [comment]
Here's the docs for TabbedPage:
https://developer.xamarin.com/api/type/Xamarin.Forms.TabbedPage/

Here's a sample that uses data binding:
https://developer.xamarin.com/samples/xamarin-forms/Navigation/TabbedPage/
