### ISSUE TITLE
[Update] 20 ConfirmNavigation

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Samples-Forms#62]
### Sample

20-ConfirmNavigation

#### Reason for Update

This sample is currently stubbed and needs actual implementation.

TODO

- Create a basic UI with a Switch bound to a bool in the ViewModel
- Try to Navigate away to another Page return the value of the bool
- This should probably be wrapped in a Tabbed Page so we can demo both `IConfirmNavigation` and `IConfirmNavigationAsync` in different tabs.

**Comment by almirvuk** [comment]
If this one is also available for implementation, Can I take it? :)

**Comment by dansiegel** [comment]
sounds good... thanks for the help

**Comment by dansiegel** [comment]
closed by #77
