### ISSUE TITLE
[Request] SkiaSharp + Prism

### ISSUE THREAD

**Issue by ScarlettCode** [PrismLibrary/Prism-Samples-Forms#71]
### Sample

A sample showing how to use [SkiaSharp](https://github.com/mono/SkiaSharp) and prism together.

Really I just need help answering this [question](https://github.com/mono/SkiaSharp/issues/925) and a sample would be a good place

**Comment by dansiegel** [comment]
@ScarlettCode I'm going to close this for now as I'm not sure that this is really something we need. Feel free to ping me on Slack though and we can discuss the issue you've posted on the Skia repo.
