### ISSUE TITLE
50 - UWP Rg.Plugins.Popup initialization missing

### ISSUE THREAD

**Issue by DellaMoraWalter** [PrismLibrary/Prism-Samples-Forms#78]
According to [documentation](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started#universal-windows-platform) Rg.Plugins.Popup initialization is required in App.xaml.cs.

`Rg.Plugins.Popup.Popup.Init();
Xamarin.Forms.Forms.Init(e, Rg.Plugins.Popup.Popup.GetExtraAssemblies());`

in place of

`Xamarin.Forms.Forms.Init(e);`

Thanks for your good job
Walter

**Comment by dansiegel** [comment]
@DellaMoraWalter you are 100% correct. Thanks for the catch.
