### ISSUE TITLE
[Request] RegisterForNavigation Sample

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Samples-Forms#80]
### Sample

Add a sample to show various ways to Register Views for Navigation.

- Basic Register View
- Register View + ViewModel
- Register View with Custom Name
- Register View with Platform Specific Overrides
- Register View with Idiom Specific Overrides

#### Reason for Update

We want to show users how to Register Views for Navigation depending on their workflow.

**Comment by almirvuk** [comment]
Can I take this one also? 😊

**Comment by almirvuk** [comment]
We can close this one now? 😄
