### ISSUE TITLE
ContosoCookbook: Can not resolve reference 'System.Threading.Tasks.Extensions'

### ISSUE THREAD

**Issue by ppedro74** [PrismLibrary/Prism-Samples-Forms#82]
### Description

Can't compile ContosoCookbook with Visual Studio 2017 (15.9.19). 

#### Error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `Unity.Abstractions`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `Unity.Abstractions`.	ContosoCookbook.Droid

#### Details:
ContosoCookbook.Droid -> Prism.Unity.Forms 7.2.0.1422 -> Unity.Container 5.11.1 -> Unity.Abstractions 5.11.1 -> System.Threading.Task.Extensions (>= 4.5.2)

I added the package System.Threading.Task.Extensions 4.5.2, 4.5.3, 4.6.0-preview
Still the same issue.

Visual Studio 2019 is not ready for production code.

Please advise.

**Comment by brianlagunas** [comment]
Visual Studio is most definitely ready for production code. It builds fine in VS 2019.  I do not have VS2017 installed and I am unable to test this scenario. You have the source code available. Feel free to modify your local copy s it builds in your environment. Or just install VS2019 side-by-side so you can compile the samples with no problems.

**Comment by ppedro74** [comment]
@brianlagunas Thanks for quick help... closing the ticket.
 
Another member of my team has some issues with Visual Studio 2019 and Android, 
someone pointed this url as reference:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview

**"This release is not "go-live" and not intended for use on production computers or for creating production code."**

**Comment by brianlagunas** [comment]
That's because they are reading the "**Preview**" release nots, not the RTM version which is here:

https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

**Comment by ppedro74** [comment]
my mistake, last time i sync there was some issues VS2019 + Android.
What I was looking for is a Prism version supported by VS2017, just in case we can't use VS2019.

**Comment by brianlagunas** [comment]
Prism works fine in VS2017. Where you might run into issues are the platforms you are trying to use in VS2017.  For example, .NET Core3  is not supported on VS2017. This is not a Prism issue. This is a platform/tooling issue.
