### ISSUE TITLE
LaunchScreen not working on iPhone 11 iOS 13.3 simulator

### ISSUE THREAD

**Issue by GioviQ** [PrismLibrary/Prism-Samples-Forms#84]
### Description

I am running https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/02-ServiceRegistration on iPhone 11 iOS 13.3 simulator, but instead of LaunchScreen I see only a blue screen.

Visual Studio Community 19 v.16.4.3 is paired with a MacBook Air with Catalina and the last version of Xcode.

**Comment by GioviQ** [comment]
It is working on real device.

**Comment by brianlagunas** [comment]
This really isn't a Prism issue. If XF has issues running on devices, then XF will need to fix this. Also, I'm not so concerned with what versions of simulators work with the samples. I'm 
more concerned that the samples show the code necessary to achieve the feature.
