### ISSUE TITLE
Failed to run the [05-EventAggregator] sample!

### ISSUE THREAD

**Issue by winsonet** [PrismLibrary/Prism-Samples-Forms#89]
I tried to run the sample in mac os with visual studio 2019, I didn't change anything, and just confusion that why the sample doesn't need to use the ```Prism.Events``` namespace? 

but even I did it, it still failed as below :

```AppDelegate.cs```
![image](https://user-images.githubusercontent.com/1869995/79685436-67095d80-826b-11ea-8cfb-dc7a1eb788a3.png)

```MainActivity.cs```
![image](https://user-images.githubusercontent.com/1869995/79685451-7d171e00-826b-11ea-82c5-151e9dfde8f6.png)

**Comment by jbachelor** [comment]
Hi @winsonet. I get similar results. Let me dig in a little bit and see if I can get this sample updated. Back with more soon.
