### ISSUE TITLE
Prism_forms on iOS with "link all" didn't work

### ISSUE THREAD

**Issue by PBum** [PrismLibrary/Prism-Samples-Forms#9]
Hello,

I use prism_forms with xamarin and if I activate the "link all" option on projectproperties - iOS build I get the error 

> Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch

To get it work to this point I must exclude some dlls from linking:

> --linkskip=Microsoft.Practices.ServiceLocation --linkskip=Microsoft.Practices.Unity --linkskip=Prism --linkskip=Prism.Forms --linkskip=Prism.Unity.Forms 

Can you help me?

Sincerly
Peter

**Comment by brianlagunas** [comment]
Wow!  I am so sorry I have not responded.  This completely fell through the cracks.  Did you ever get this resolved?

**Comment by brianlagunas** [comment]
I'm going to assume this was figured out.  If not, let me know.
