### ISSUE TITLE
[Request] Unit Testing w/ Basic and Advanced INavigationService

### ISSUE THREAD

**Issue by MRoy-BTE** [PrismLibrary/Prism-Samples-Forms#96]
### Sample

Unit Testing w/ Basic and Advanced INavigationService. 

#### Reason for Update

Currently there are no samples of how to best implement unit testing using this framework. We cannot mock something like NavigateAsync(pageName, params, useModal, animated) because it is an extension method. It would be nice to get a better understanding of best practices to handle such things prism specific. Another example of this would be unit testing ViewModels that use EventAggregator.

**Comment by dansiegel** [comment]
This isn't something that we're going to add to the Samples, but may be something that I cover in a future YouTube video.
